[project]
name = "debug-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo[recommended]>=0.13.15",
    "numpy>=2.2.6",
    "seaborn>=0.13.2",
    "uv-bump>=0.1.2",
]
